=== iLesnoy/epamTask3/resources/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.org/tariffs"
        xmlns:tns="http://www.example.org/tariffs"
        elementFormDefault="qualified">

    <element name="tariffs">
        <complexType>
            <sequence>
                <element ref="tns:tariff" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="tariff" type="tns:Tariff" abstract="true"/>
    <element name="constant-tariff" type="tns:constantTariff" substitutionGroup="tns:tariff"/>
    <element name="temporary-tariff" type="tns:temporaryTariff" substitutionGroup="tns:tariff"/>


    <complexType name="Tariff">
        <sequence>
            <element name="name" type="string"/>
            <element name="year" type="gYear"/>
            <element name="operator-name" type="string"/>
            <element name="payroll" type="positiveInteger"/>
            <element name="call-prices" type="tns:CallPrices"/>
            <element name="sms-price" type="positiveInteger"/>
            <element name="parameters" type="tns:parameters"/>
        </sequence>
        <attribute name="tariff-id" type="tns:tariffID" use="required"/>
        <attribute name="title" use="optional" type="string"/>
    </complexType>

    <complexType name="constantTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="constant-tariff-parameters" type="tns:constantTariffParameters"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="temporaryTariff">
        <complexContent>
            <extension base="tns:Tariff">
                <sequence>
                    <element name="temporary-tariff-parameters" type="tns:temporaryTariffParameters"/>
                </sequence>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="tariffID">
        <restriction base="ID">
            <pattern value="\w\d{1,10}"/>
        </restriction>
    </simpleType>

    <simpleType name="name">
        <restriction base="string">
            <enumeration value="retirement"/>
            <enumeration value="business"/>
            <enumeration value="gigi"/>
        </restriction>
    </simpleType>

    <simpleType name="operator-name">
        <restriction base="string">
            <enumeration value="A1"/>
            <enumeration value="MTC"/>
            <enumeration value="Life"/>
        </restriction>
    </simpleType>


    <simpleType name="payroll">
        <restriction base="unsignedInt">
            <enumeration value="0"/>
            <enumeration value="100000"/>
        </restriction>
    </simpleType>

    <complexType name="CallPrices">
        <sequence>
            <element name="on-net-calls" type="string"/>
            <element name="out-of-network-calls" type="string"/>
            <element name="calls-to-landlines" type="string"/>
        </sequence>
    </complexType>

    <simpleType name="sms-price">
        <restriction base="unsignedInt">
            <enumeration value="0"/>
            <enumeration value="100000"/>
        </restriction>
    </simpleType>

    <complexType name="parameters">
        <sequence>
            <element name="presence-of-a-favorite-number" type="string"/>
            <element name="tariffication" type="string"/>
            <element name="tariff-connection-fee" type="string"/>
        </sequence>
    </complexType>

    <simpleType name="constantTariffParameters">
        <restriction base="string">
            <enumeration value="presence of a favorite number(0-n rub per minute)"/>
            <enumeration value="tariffication(12-sec,minute)"/>
            <enumeration value="tariff connection fee(0-n rub)"/>
        </restriction>
    </simpleType>

    <simpleType name="temporaryTariffParameters">
        <restriction base="string">
            <enumeration value="promotional rate tariff"/>
            <enumeration value="temporary"/>
            <enumeration value="user's personal account"/>
        </restriction>
    </simpleType>
</schema>

=== iLesnoy/epamTask3/resources/test.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/tariffs"
         xsi:schemaLocation="http://www.example.org/tariffs/resources/schema.xsd">

    <constant-tariff number="">
        <name></name>
        <tariffID>
            <call-prices>0</call-prices>
            <sms-price>10</sms-price>
        </tariffID>
        <operator-name>A1</operator-name>
        <payroll> </payroll>
        <parameters></parameters>
        <constant-tariff-type> </constant-tariff-type>
        <constant-tariff-parameters> </constant-tariff-parameters>
    </constant-tariff>

=== iLesnoy/epamTask3/resources/tariffs.xml
<?xml version="1.0" encoding="UTF-8"?>
<tariffs xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://www.example.org/tariffs"
         xsi:schemaLocation="http://www.example.org/tariffs/resources/schema.xsd">

   <constant-tariff tariff-id="a1">
     <name>business tariff</name>
     <operator-name>A1</operator-name>
     <payroll>20</payroll>
     <call-prices>on-net calls</call-prices>
     <sms-price>2</sms-price>
     <parameters>tariff connection fee</parameters>
     <constant-tariff-type>constant tariff</constant-tariff-type>
     <constant-tariff-parameters>presence of a favorite number</constant-tariff-parameters>
   </constant-tariff>

    <constant-tariff tariff-id="a2">
        <name>privet</name>
        <operator-name>life</operator-name>
        <payroll>10</payroll>
        <call-prices>out-of-network calls</call-prices>
        <sms-price>1</sms-price>
        <parameters>tariffication</parameters>
        <constant-tariff-type>constant tariff</constant-tariff-type>
        <constant-tariff-parameters>presence of a favorite number</constant-tariff-parameters>
    </constant-tariff>

    <temporary-tariff tariff-id="a3">
        <name>poka</name>
        <operator-name>a1</operator-name>
        <payroll>7</payroll>
        <call-prices>calls to landlines</call-prices>
        <sms-price>2</sms-price>
        <parameters>tariff connection fee</parameters>
        <temporary-tariff-parameters>temporary</temporary-tariff-parameters>
    </temporary-tariff>

</tariffs>
